name: Daily Update

on:
  schedule:
    # 每天 UTC 16:00 运行（北京时间 0:00）
    - cron: '0 16 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Run update task
        run: deno task update

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: daily update $(date +%Y-%m-%d)"
          git push